# Generated by Django 5.2.1 on 2025-07-06 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreedomPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('education', 'Education'), ('women', 'Women Safety'), ('judiciary', 'Judiciary'), ('corruption', 'Corruption'), ('police', 'Police Injustice'), ('farmer', 'Farmer Rights'), ('child', 'Child Rights'), ('public', 'Public Issues')], max_length=20)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('support_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
