# Generated by Django 5.2.1 on 2025-07-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedompost',
            name='support',
            field=models.IntegerField(default=0),
        ),
    ]
