# Generated by Django 5.2.1 on 2025-07-05 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpinghand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpoffer',
            old_name='submitted_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='helpoffer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='helpoffer',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='helpoffer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='helpoffer',
            name='title',
        ),
        migrations.AddField(
            model_name='helpoffer',
            name='help_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Education', 'Education'), ('Money', 'Money'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
