# Generated by Django 5.2.1 on 2025-07-05 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corruptionreport',
            old_name='date_submitted',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='corruptionreport',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='corruptionreport',
            name='is_investigated',
        ),
        migrations.AddField(
            model_name='corruptionreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='corruptionreport',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='corruption_proofs/'),
        ),
    ]
